name: Compile bot

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "ddbot"
  repository_dispatch:
    types: ddbot

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Compile
      run: |
        cd ./ddbot/

        go mod download
        go mod tidy

        export CGO_ENABLED=0
        export GOOS=linux

        export GOARCH=amd64
        go build -o ~/ddbot-amd64 ddbot.go

        export GOARCH=arm64
        go build -o ~/ddbot-arm64 ddbot.go

        export GOARCH=arm
        go build -o ~/ddbot-arm ddbot.go
        
    - name: Commit files
      run: |
        git reset --hard
        
        ls -l ./ddbot
        
        cp -rf ~/ddbot-amd64 ./ddbot
        cp -rf ~/ddbot-arm64 ./ddbot
        cp -rf ~/ddbot-arm ./ddbot
        
        git config --local user.email "e.akimoto.akira@gmail.com"
        git config --local user.name "Github-Action"
        git commit -m "Compile bot by github action" -a

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
